repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        entry: black
        exclude: "(.*art_techniques.py|.*pb2.*py)"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
    - id: pyright
      name: pyright
      exclude: ".*art_techniques.py"
      entry: pyright
      language: system
      types_or: [python, pyi]
