adjacency_list:
- - start
  - d1
- - d1
  - d2
  - d3
- - d3
  - d4
- - d4
  - d2
- - d2
  - end
init_info:
  d1:
    class: PerfectDetector
    config: null
    module: example_detectors
  d2:
    class: PerfectDetector
    config: null
    module: example_detectors
  d3:
    class: PerfectDetector
    config: null
    module: example_detectors
  d4:
    class: PerfectDetector
    config: null
    module: example_detectors
