WindowsDiscoveryExploitableService:
  cve:
    - CVE-2023-28325
    - CVE-2021-32526
    - CVE-2020-10048
    - CVE-2023-23696
    - CVE-2023-7079
    - CVE-2016-10651
    - CVE-2019-1899
    - CVE-2022-28651
    - CVE-2020-10049
    - CVE-2014-125055
  port: 8010
  protocol: tcp
  version: 1
  description: exploitable service in the discovery killchain phase
  decoy: False
  name: WindowsDiscoveryExploitableService
WindowsImpactExploitableService:
  cve:
    - CVE-2023-2030
    - CVE-2023-2987
    - CVE-2022-23556
    - CVE-2022-41961
    - CVE-2023-27979
    - CVE-2022-41156
    - CVE-2023-41898
    - CVE-2017-20180
    - CVE-2019-16007
    - CVE-2021-34572
  port: 8020
  protocol: tcp
  version: 1
  description: exploitable service in the impact killchain phase
  decoy: False
  name: WindowsImpactExploitableService
WindowsLateralMovementExploitableService:
  cve:
    - CVE-2021-21329
    - CVE-2018-1106
    - CVE-2019-18246
    - CVE-2020-29032
    - CVE-2022-33689
    - CVE-2020-7817
    - CVE-2019-3798
    - CVE-2021-24148
    - CVE-2018-0195
    - CVE-2007-4961
  port: 8030
  protocol: tcp
  version: 1
  description: exploitable service in the lateral movement killchain phase
  decoy: False
  name: WindowsLateralMovementExploitableService
WindowsPrivilegeEscalationExploitableService:
  cve:
    - CVE-2023-29463
    - CVE-2023-4816
    - CVE-2022-21712
    - CVE-2022-32219
    - CVE-2023-21512
    - CVE-2021-27772
    - CVE-2023-1584
    - CVE-2020-25168
    - CVE-2023-33972
    - CVE-2021-43786'
  port: 8040
  protocol: tcp
  version: 1
  description: exploitable service in the privilege escalation killchain phase
  decoy: False
  name: WindowsPrivilegeEscalationExploitableService
