# Network Configuration
network:
  name: network_foo
  desc: A network that has 6 subnets with 5 hosts each

# Topology Definition
topology:
  - MainRouter:
      - wan_subnet
      - SubnetA:
        - Host1
        - Host2
        - Host3
        - Host4
        - Host5
      - SubnetB:
        - Host6
        - Host7
        - Host8
        - Host9
        - Host10
      - SubnetCRouter:
        - SubnetC:
          - Host11
          - Host12
          - Host13
          - Host14
          - Host15
      - SubnetD:
        - Host16
        - Host17
        - Host18
        - Host19
        - Host20
      - SubnetE:
        - Host21
        - Host22
        - Host23
        - Host24
        - Host25
      - SubnetF:
        - Host26
        - Host27
        - Host28
        - Host29
        - Host30

# Routers
routers:
  - name: MainRouter
    default_route: wan_subnet
    routes:
      - SubnetA
      - SubnetB
      - SubnetCRouter
      - SubnetD
      - SubnetE
      - SubnetF
    firewall:
      - src_subnet: SubnetA
        src_hosts:
          - Host1
          - Host2
          - Host3
          - Host4
          - Host5
        dest_subnet: SubnetB
        dest_hosts:
          - Host6
          - Host7
          - Host8
          - Host9
          - Host10
        allow_ports:
          - 80: tcp
          - 443: tcp
      - src_subnet: SubnetB
        allow_services:
          - SSH
          - FTP
          - ICMP
      - src_subnet: SubnetC
        src_hosts:
          - Host11
          - Host12
          - Host13
          - Host14
          - Host15
        dest_subnet: SubnetD
        dest_hosts:
          - Host16
          - Host17
          - Host18
          - Host19
          - Host20
        allow_ports:
          - 80: tcp
          - 443: tcp
          - 123: udp
      - src_subnet: SubnetD
        allow_services:
          - SSH
          - FTP
          - ICMP
      - src_subnet: SubnetE
        src_hosts:
          - Host21
          - Host22
          - Host23
          - Host24
          - Host25
        dest_subnet: SubnetF
        dest_hosts:
          - Host26
          - Host27
          - Host28
          - Host29
          - Host30
        allow_ports:
          - 80: tcp
          - 443: tcp
      - src_subnet: SubnetF
        allow_services:
          - SSH
          - FTP

# Subnets
subnets:
  - name: SubnetA
    default_route: MainRouter
    ip_range: 192.168.1.0/24

  - name: SubnetB
    default_route: MainRouter
    ip_range: 192.168.2.0/24

  - name: SubnetC
    default_route: MainRouter
    ip_range: 192.168.3.0/24

  - name: SubnetD
    default_route: MainRouter
    ip_range: 192.168.4.0/24

  - name: SubnetE
    default_route: MainRouter
    ip_range: 192.168.5.0/24

  - name: SubnetF
    default_route: MainRouter
    ip_range: 192.168.6.0/24

# Hosts
hosts:
  - name: Host1
    type: Server
    subnet: SubnetA

  - name: Host2
    type: Workstation
    subnet: SubnetA

  - name: Host3
    type: Workstation
    subnet: SubnetA

  - name: Host4
    type: Workstation
    subnet: SubnetA

  - name: Host5
    type: Workstation
    subnet: SubnetA

  - name: Host6
    type: Server
    subnet: SubnetB

  - name: Host7
    type: Workstation
    subnet: SubnetB

  - name: Host8
    type: Workstation
    subnet: SubnetB

  - name: Host9
    type: Workstation
    subnet: SubnetB

  - name: Host10
    type: Workstation
    subnet: SubnetB

  - name: Host11
    type: Server
    subnet: SubnetC

  - name: Host12
    type: Workstation
    subnet: SubnetC

  - name: Host13
    type: Workstation
    subnet: SubnetC

  - name: Host14
    type: Workstation
    subnet: SubnetC

  - name: Host15
    type: Workstation
    subnet: SubnetC

  - name: Host16
    type: Server
    subnet: SubnetD

  - name: Host17
    type: Workstation
    subnet: SubnetD

  - name: Host18
    type: Workstation
    subnet: SubnetD

  - name: Host19
    type: Workstation
    subnet: SubnetD

  - name: Host20
    type: Workstation
    subnet: SubnetD

  - name: Host21
    type: Server
    subnet: SubnetE

  - name: Host22
    type: Workstation
    subnet: SubnetE

  - name: Host23
    type: Workstation
    subnet: SubnetE

  - name: Host24
    type: Workstation
    subnet: SubnetE

  - name: Host25
    type: Workstation
    subnet: SubnetE

  - name: Host26
    type: Server
    subnet: SubnetF

  - name: Host27
    type: Workstation
    subnet: SubnetF

  - name: Host28
    type: Workstation
    subnet: SubnetF

  - name: Host29
    type: Workstation
    subnet: SubnetF

  - name: Host30
    type: Workstation
    subnet: SubnetF
