#questions:
#  - How do we feel about this CamelCase? (I generally prefer CamelCase for classes and snake_case for most everything else, but that's just my $0.02)
#  - I 86'd the inbound/outbound distinction under the router firewall rules. Anyone think we need that?
#  - I added protocol to the services. Is this too superflous? (i.e. tcp/udp)
#  - Should defaults always be explicit or can we write the defaults into the code and override as needed?

# Network Configuration
network:
  name: network_foo
  desc: A network that foos all the bars

# Topology Definition
topology:
  - MainRouter:
    - wan_subnet    # adding this so the MainRouter can have a sane default route
    - SubnetA:
      - Host1
      - Host2
    - SubnetB:
      - Host3
    - SubnetCRouter:
      - SubnetC:
        - Host4
        - Host5
    - SubnetD
    - SubnetE

# Routers
routers:
  - name: MainRouter
    # represents the state of the routing table or subnets this router "knows" about
    default_route: wan_subnet
    routes:
      - SubnetA
      - SubnetB
      - SubnetCRouter    # this would inherit all defined routes from SubnetCRouter
                         # i.e. MainRouter would know about SubnetC because SubnetCRouter
                         # has that route defined
      #- SubnetD    # if subnet not defined in "routes" assume no route to said subnet?
    firewall:
      - src_subnet: SubnetA
        src_hosts:    # if src_hosts is undefined default to all hosts on src subnet?
          - Host1
          - Host2
        dest_subnet: SubnetB
        dest_hosts:    # if dest_hosts is undefined default to all hosts on dest subnet?
          - Host3
        #allow_ports: [80, 443]  # Allow HTTP (port 80) and HTTPS (port 443) traffic
        allow_ports:    # Do we want to specify protocol? (i.e. tcp/udp)
          - 80: tcp
          - 443: tcp
      - src_subnet: SubnetB
        allow_services: [SSH, FTP, ICMP]  # Allow SSH, FTP, and ping
      - src_subnet: SubnetC    # if no rules defined for subnet, assume allow all?
      #- src_subnet: subnet_not_listed_in_fw_rules    # if subnet not defined, assume allow all?

# Child Router (nested under MainRouter)
  - name: SubnetCRouter
    default_route: MainRouter    # ability to use either subnet or router to specify default route
                                 # this gives us the freedom to not have to define networks between routers
                                 # i.e. MainRouter <--> SubnetARouter
    routes:
      - subnetC
    firewall:
      # this would allow all hosts on SubnetA to hit any host on SubnetB on the defined ports
      - source_subnet: SubnetA
        allow_ports:
          - 80: tcp
          - 443: tcp
          - 123: udp
      # this would allow all hosts on SubnetB to connect only to Host3 via the defined services
      - source_subnet: SubnetB
        dest_hosts:
          - Host3
        allow_services: [SSH, FTP]  # Allow SSH and FTP services

# Subnets
subnets:
  - name: SubnetA
    default_route: MainRouter
    ip_range: 192.168.1.0/24

  - name: SubnetB
    default_route: MainRouter
    ip_range: 192.168.2.0/24

  - name: SubnetC
    default_route: SubnetCRouter
    ip_range: 192.168.3.0/24

# Hosts
hosts:
  - name: Host1
    type: Server
    subnet: SubnetA
    # host based firewall
    firewall:
      - allow_icmp: true    # this should prob be the default
      - name: allow foo service
        service: foo    # must be defined in service definitions to use this key
        port: 12345     # ability to override default port for defined service?
        src: [Host2, Host3, SubnetA]    # default to "allow all" if not defined?
                                        # would be nice to have the ability to specify hosts and/or subnets here

  - name: Host2
    type: Workstation
    subnet: SubnetA
    firewall:    # if firewall not defined or empty assume "allow all" for ease of use?
                 # or maybe default to allowing all defined services for the host type?

  - name: Host3
    type: Workstation
    subnet: SubnetC
    firewall:
      - name: allow custom service not in service definitions
        port: 54321
        proto: tcp
        src: []    # if src undefined default to allow all

  - name: Host4
    type: Printer
    subnet: SubnetC
