action_module_path: "cyberwheel.blue_actions.actions"
action_space_module_path: "cyberwheel.blue_agents.action_space"

actions:
  nothing: # Unique name for this action
    module: Nothing # Module this action's class is located in
    class: Nothing # The action class's name
    configs: # List of config file names this action needs. Must be in cyberwheel/resources/configs
    reward:
      immediate: 0.0 # Reward gained for executing this action.
      recurring: 0.0 # Reward gained for on this step and all subsequent steps after taking this action.
    action_space_args:
      type: standalone
    shared_data:

  decoy0:
    module: DeployDecoyHost
    class: DeployDecoyHost
    configs:
      decoy_hosts: decoy_server_hosts.yaml
      host_definitions: host_defs_services.yaml
      services: windows_exploitable_services.yaml
    reward:
      immediate: -20.0
      recurring: -2.0
    action_space_args:
      type: subnet
    shared_data:
      - isolate_data

# Shared data is additional data that is shared by blue actions
# The actions define what data they want to use
# The type of the data is defined here.
# Can be a list, set, dict or another object that implements a `clear()` method.
shared_data:
  isolate_data:
    module: cyberwheel.blue_actions.shared_data.IsolateData
    class: IsolateData
    # OPTIONAL. Parameters for initializing the class.
    args:
      size: 4

action_space:
  module: discrete
  class: DiscreteActionSpace
  args:
