# Example decoy hosts
decoy1:
  type: mail_server
  reward: -4
  recurring_reward: -0.2
  services:
  - WindowsDiscoveryExploitableService
  - WindowsLateralMovementExploitableService
  - WindowsPrivilegeEscalationExploitableService
  - WindowsImpactExploitableService
decoy2:
  type: file_server
  reward: -6
  recurring_reward: -0.3
  services:
  - WindowsDiscoveryExploitableService
  - WindowsLateralMovementExploitableService
  - WindowsPrivilegeEscalationExploitableService
  - WindowsImpactExploitableService
decoy3:
  type: web_server
  reward: -2
  recurring_reward: -0.1
  services:
  - WindowsDiscoveryExploitableService
  - WindowsLateralMovementExploitableService
  - WindowsPrivilegeEscalationExploitableService
  - WindowsImpactExploitableService
decoy4:
  type: ssh_jump_server
  reward: -2
  recurring_reward: -0.1
  services:
  - WindowsDiscoveryExploitableService
  - WindowsLateralMovementExploitableService
  - WindowsPrivilegeEscalationExploitableService
  - WindowsImpactExploitableService
decoy5:
  type: proxy_server
  reward: -4
  recurring_reward: -0.2
  services:
  - WindowsDiscoveryExploitableService
  - WindowsLateralMovementExploitableService
  - WindowsPrivilegeEscalationExploitableService
  - WindowsImpactExploitableService
decoy6:
  type: workstation
  reward: -4
  recurring_reward: -0.2
  services:
  - WindowsDiscoveryExploitableService
  - WindowsLateralMovementExploitableService
  - WindowsPrivilegeEscalationExploitableService
  - WindowsImpactExploitableService
