# Network Configuration
network:
  name: network_foo
  desc: A network that foos all the bars

# Topology Definition
topology:
  - MainRouter:
    - SubnetA:
      - HostA1
      - HostA2
      - HostA3
      - HostA4
      - HostA5
    - SubnetB:
      - HostB1
      - HostB2
      - HostB3
      - HostB4
      - HostB5
    - SubnetCRouter:
      - SubnetC:
        - HostC1
        - HostC2
        - HostC3
        - HostC4
        - HostC5
    - SubnetD:
      - HostD1
      - HostD2
      - HostD3
      - HostD4
      - HostD5
    - SubnetE:
      - HostE1
      - HostE2
      - HostE3
      - HostE4
      - HostE5

# Routers
routers:
  - name: MainRouter
    default_route: wan_subnet
    routes:
      - SubnetA
      - SubnetB
      - SubnetCRouter
    firewall:
      - src_subnet: SubnetA
        src_hosts:
          - HostA1
          - HostA2
        dest_subnet: SubnetB
        dest_hosts:
          - HostB1
        allow_ports:
          - 80: tcp
          - 443: tcp

  - name: SubnetCRouter
    default_route: MainRouter
    routes:
      - SubnetC
    firewall:
      - source_subnet: SubnetA
        allow_ports:
          - 80: tcp
          - 443: tcp
          - 123: udp
      - source_subnet: SubnetB
        dest_hosts:
          - HostB1
        allow_services: [SSH, FTP]

# Subnets
subnets:
  - name: SubnetA
    default_route: MainRouter
    ip_range: 192.168.1.0/24

  - name: SubnetB
    default_route: MainRouter
    ip_range: 192.168.2.0/24

  - name: SubnetC
    default_route: SubnetCRouter
    ip_range: 192.168.3.0/24

  - name: SubnetD
    default_route: MainRouter
    ip_range: 192.168.4.0/24

  - name: SubnetE
    default_route: MainRouter
    ip_range: 192.168.5.0/24

# Hosts
hosts:
  - name: HostA1
    type: Server
    subnet: SubnetA

  - name: HostA2
    type: Workstation
    subnet: SubnetA

  - name: HostA3
    type: Workstation
    subnet: SubnetA

  - name: HostA4
    type: Printer
    subnet: SubnetA

  - name: HostA5
    type: Server
    subnet: SubnetA

  - name: HostB1
    type: Server
    subnet: SubnetB

  - name: HostB2
    type: Workstation
    subnet: SubnetB

  - name: HostB3
    type: Workstation
    subnet: SubnetB

  - name: HostB4
    type: Printer
    subnet: SubnetB

  - name: HostB5
    type: Server
    subnet: SubnetB

  - name: HostC1
    type: Server
    subnet: SubnetC

  - name: HostC2
    type: Workstation
    subnet: SubnetC

  - name: HostC3
    type: Workstation
    subnet: SubnetC

  - name: HostC4
    type: Printer
    subnet: SubnetC

  - name: HostC5
    type: Server
    subnet: SubnetC

  - name: HostD1
    type: Server
    subnet: SubnetD

  - name: HostD2
    type: Workstation
    subnet: SubnetD

  - name: HostD3
    type: Workstation
    subnet: SubnetD

  - name: HostD4
    type: Printer
    subnet: SubnetD

  - name: HostD5
    type: Server
    subnet: SubnetD

  - name: HostE1
    type: Server
    subnet: SubnetE

  - name: HostE2
    type: Workstation
    subnet: SubnetE

  - name: HostE3
    type: Workstation
    subnet: SubnetE

  - name: HostE4
    type: Printer
    subnet: SubnetE

  - name: HostE5
    type: Server
    subnet: SubnetE
