host_type_config: resources/metadata/host_defs_services.json
hosts:
  admin_workstation:
    firewall:
    - name: allow SSH
      port: 22
      src: allow SSH
    routes:
    subnet: user_subnet
    type: workstation
  dmz01:
    firewall:
    routes:
    subnet: dmz_subnet
    type: workstation
  dmz02:
    firewall:
    routes:
    subnet: dmz_subnet
    type: workstation
  dmz_jump_box:
    firewall:
    - name: allow SSH
      port: 22
    routes:
    subnet: dmz_subnet
    type: workstation
  server01:
    firewall:
    routes:
    subnet: server_subnet
    type: web_server
  server02:
    firewall:
    routes:
    subnet: server_subnet
    type: web_server
  server03:
    firewall:
    routes:
    subnet: server_subnet
    type: web_server
  user01:
    firewall:
    routes:
    - dest: 192.168.2.0/24
      via: 192.168.0.1
    subnet: user_subnet
    type: workstation
  user02:
    firewall:
    - name: foo
      port: 3389
      src: foo
    routes:
    subnet: user_subnet
    type: workstation
  user03:
    firewall:
    routes:
    subnet: user_subnet
    type: workstation
interfaces:
  user01:
  - dmz01
  dmz01:
  - server01
network:
  desc: default description
  name: 10-host-network
routers:
  core_router:
    default_route:
    firewall:
    routes:
    - dest: 10.0.0.0/8
      via: 10.0.0.1
    routes_by_name:
    - user_subnet
subnets:
  dmz_subnet:
    firewall:
    ip_range: 192.168.2.0/24
    router: core_router
  server_subnet:
    firewall:
    - dest: server_subnet
      name: allow admin to server_subnet
      src: allow admin to server_subnet
    - dest: server_subnet
      name: allow DNS
      port: 53
      src: allow DNS
    - dest: server_subnet
      name: allow DHCP
      port: 68
      proto: udp
      src: allow DHCP
    ip_range: 192.168.1.0/24
    router: core_router
  user_subnet:
    dns_server: 192.168.0.1
    firewall:
    - name: allow all from server_subnet
      src: allow all from server_subnet
    - name: allow ssh from dmz_jump_box
      port: 22
      src: allow ssh from dmz_jump_box
    ip_range: 192.168.0.0/24
    router: core_router
topology:
  core_router:
    dmz_subnet:
    - dmz01
    - dmz02
    - dmz_jump_box
    server_subnet:
    - server01
    - server02
    - server03
    user_subnet:
    - user01
    - user02
    - user03
    - admin_workstation
