actions:
  # Name of the module
  Nothing:
    # Unique name for this action
    name: nothing
    # The class's name
    class: Nothing
    # Configs that this action needs
    # Key is what the class expects the config to be named.
    # Value is the name of the file found in cyberwheel/resources/configs
    configs:
    # Rewards for this action
    reward:
      immediate: 0
      recurring: 0
    # Type of action. Can be host, subnet, or standalone
    # host means this actions is repeated for each host. I.e. it's dependent on hosts
    # subnet means this action is repeated for each subnet. I.e it's dependent on subnets
    # standalone means this action is not repeated. I.e. it's independent of the network
    type: standalone
    # List of shared data this action needs from the blue agent.
    shared_data:

  DeployDecoyHost:
    name: decoy0
    class: DeployDecoyHost
    configs: 
      decoy_hosts: decoy_server_hosts.yaml
      host_definitions: host_definitions.yaml
    reward: 
      immediate: -10
      recurring: -1
    type: subnet
    shared_data:
      - decoy_list

  RemoveDecoyHost:
    name: remove_decoy
    class: RemoveDecoyHost
    configs:
    reward:
        immediate: 0
        recurring: 0
    type: subnet
    shared_data:

# Shared data is additional data that is shared by blue actions
# The actions define what data they want to use
# The type of the data is defined here.
# Can be a list, set, or dict
shared_data:
  decoy_list: list 

