from cyberwheel.red_agents.strategies.red_strategy import RedStrategy
from cyberwheel.red_agents.strategies.dfs_impact import DFSImpact
from cyberwheel.red_agents.strategies.server_downtime import ServerDowntime